Repository miraclee1226/Fandom-k, pull requests merged in 2024-05, with the labels that each got.

#19 [Feature] Tab, RactangleImage, RoundImage 컴포넌트 개발
  src/assets/Image_Idol.png
  src/components/Image/RectangleImage/RectangleImage.jsx
  src/components/Image/RectangleImage/RectangleImage.module.scss
  src/components/Image/RoundImage/RoundImage.jsx
  src/components/Image/RoundImage/RoundImage.module.scss
  src/components/Tab/Tab.jsx
  src/components/Tab/Tab.module.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: enhancement

#30 [Feature] Chart 컴포넌트 개발
  src/assets/icons/chart.svg
  src/components/ChartItem/ChartItem.jsx
  src/components/Tab/Tab.jsx
  src/mockData/femaleData.json
  src/mockData/maleData.json
  src/pages/Landing.jsx
  src/pages/List.jsx
  src/pages/List.module.scss
  src/pages/ListPage/ChartSection.jsx
Labels: enhancement

#44 [이율] Refactor: supportCard jsonData와 매칭, 반응형 수정
  src/components/Card/LineGraph.jsx
  src/components/Card/LineGraph.module.scss
  src/components/Card/SupportCard.jsx
  src/components/Card/SupportCard/SupportCard.jsx
  src/components/Card/SupportCard/SupportCard.module.scss
  src/components/Card/index.js
  src/mockData/donations.json
  src/pages/List.jsx
  src/pages/List.module.scss
  src/pages/MyPage.jsx
  src/utils/timeCounter.js
Labels: refactor

#43 [Feature] Modal 컴포넌트 개발
  public/index.html
  src/assets/icons/credit.svg
  src/assets/icons/x_icon.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/Button/RadioButton/RadioButton.jsx
  src/components/Modal/CreditChargeModal/CreditChargeModal.jsx
  src/components/Modal/CreditChargeModal/index.js
  src/components/Modal/CreditWarningModal/CreditWarningModal.jsx
  src/components/Modal/CreditWarningModal/index.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/SupportModal/SupportModal.jsx
  src/components/Modal/SupportModal/index.js
  src/components/Modal/VoteModal/VoteModal.jsx
  src/components/Modal/VoteModal/index.js
  src/components/Modal/index.js
  src/index.jsx
  src/pages/Landing.jsx
  src/pages/List.jsx
  src/utils/commas.js
Labels: feat

#47 [천권희] Refactor: Credit Section 모바일 퍼스트로 수정
  src/pages/List.module.scss
Labels: refactor

#49 [천권희] Feature: CSS Sorting 적용
  .stylelintrc.json
  package-lock.json
  package.json
  src/components/Button/Button.module.scss
  src/components/Card/SupportCard/SupportCard.module.scss
  src/components/ChartItem/ChartItem.module.scss
  src/components/Image/RectangleImage/RectangleImage.module.scss
  src/components/Image/RoundImage/RoundImage.module.scss
  src/components/Layout/Layout.module.scss
  src/components/Navbar/Navbar.module.scss
  src/components/Tab/Tab.module.scss
  src/pages/Landing/Landing.module.scss
  src/pages/List.module.scss
  src/pages/MyPage.module.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: settings, refactor

#54 Refactor: Navbar 파일구조 통일 및 디자인 변경
  src/components/Navbar/Navbar.module.scss
  src/components/Navbar/index.js
  src/pages/MyPage.jsx
Labels: refactor

#55 [소혜린] Refactor: 폴더 정리 및 Chart Section 디자인 수정
  src/components/ChartItem/ChartItem.jsx
  src/components/ChartItem/ChartItem.module.scss
  src/components/ChartItem/index.js
  src/components/Image/Image.module.scss
  src/components/Image/RectangleImage/RectangleImage.jsx
  src/components/Image/RectangleImage/index.js
  src/components/Image/RoundImage/RoundImage.jsx
  src/components/Image/RoundImage/RoundImage.module.scss
  src/components/Image/RoundImage/index.js
  src/components/Image/index.js
  src/components/Tab/Tab.module.scss
  src/components/Tab/index.js
  src/pages/List.jsx
  src/pages/List.module.scss
  src/pages/ListPage/ChartSection.jsx
Labels: design, refactor

#61 [소혜린] 마이페이지 내의 관심있는 아이돌 섹션 디자인
  src/assets/icons/round_x_icon.svg
  src/components/ChartItem/ChartItem.jsx
  src/components/ChartItem/ChartItem.module.scss
  src/components/Image/Image.module.scss
  src/components/Image/RectangleImage/RectangleImage.jsx
  src/components/Image/RoundImage/RoundImage.jsx
  src/components/Layout/Layout.jsx
  src/components/Layout/Layout.module.scss
  src/components/TouchArea/TouchArea.jsx
  src/components/TouchArea/TouchArea.module.scss
  src/components/TouchArea/index.js
  src/pages/List.module.scss
  src/pages/ListPage/AddedFavoriteSection.jsx
  src/pages/MyPage.jsx
  src/pages/MyPage.module.scss
Labels: design

#59 [천권희] Refactor / Fix: pages 폴더 구조 정리, 반응형 수정
  .stylelintrc.json
  src/components/Button/ArrowButton/ArrowButton.jsx
  src/components/Button/BorderButton/BorderButton.jsx
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/Button/RadioButton/RadioButton.jsx
  src/components/Button/RoundButton/RoundButton.jsx
  src/components/Button/TextButton/TextButton.jsx
  src/components/Card/SupportCard.module.scss
  src/components/Card/SupportCard/SupportCard.jsx
  src/components/Card/SupportCard/index.js
  src/components/Card/index.js
  src/components/ChartItem/ChartItem.jsx
  src/components/Image/RectangleImage/RectangleImage.jsx
  src/components/Image/RoundImage/RoundImage.jsx
  src/components/Layout/index.js
  src/components/Modal/CreditChargeModal/CreditChargeModal.jsx
  src/components/Modal/CreditWarningModal/CreditWarningModal.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/SupportModal/SupportModal.jsx
  src/components/Modal/VoteModal/VoteModal.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/index.js
  src/components/Tab/Tab.jsx
  src/components/TouchArea/TouchArea.jsx
  src/index.js
  src/pages/Landing/Landing.jsx
  src/pages/Landing/Landing.module.scss
  src/pages/List/ChartSection.jsx
  src/pages/List/CreditSection.jsx
  src/pages/List/List.jsx
  src/pages/List/List.module.scss
  src/pages/List/SupportSection.jsx
  src/pages/List/index.js
  src/pages/MyPage/AddFavoriteSection.jsx
  src/pages/MyPage/AddedFavoriteSection.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/index.js
  src/styles/reset.scss
Labels: design, refactor

#69 [소혜린] Feat(WIP): 이미지 최적화
  src/components/ChartItem/ChartItem.jsx
  src/components/Image/RectangleImage/RectangleImage.jsx
  src/components/Image/RoundImage/RoundImage.jsx
  src/components/WebpLoader/WebpLoader.jsx
  src/components/WebpLoader/index.js
  src/hooks/useLazyImageObserver.jsx
  src/mockData/femaleData.json
  src/pages/MyPage/AddFavoriteSection.jsx
  src/pages/MyPage/AddedFavoriteSection.jsx
Labels: feat

#70 [천권희] useAsync hook 생성
  src/hooks/useAsync.js
Labels: feat

#72 [소혜린] Refactor: webp 이미지 제외 다른 파일 로딩 리팩토링
  src/components/WebpLoader/WebpLoader.jsx
Labels: refactor

#73 [천권희] Refactor: useRequest hook 수정
  src/hooks/useAsync.js
  src/hooks/useRequest.js
Labels: refactor

#74 [은동혁] Feat: ChartSection API 연결 및 더보기 기능 구현
  src/api/dispatcher.js
  src/hooks/useRequest.js
  src/pages/List/ChartSection.jsx
Labels: feat

#77 [소혜린] Feat: Vote Modal api 연동
  src/assets/icons/round_x_icon.svg
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/VoteModal/VoteModal.jsx
  src/components/TouchArea/TouchArea.jsx
  src/components/TouchArea/index.js
  src/hooks/useTouchArea.js
  src/pages/List/ChartSection.jsx
  src/pages/MyPage/AddedFavoriteSection.jsx
  src/pages/MyPage/DeleteIcon.jsx
  src/pages/MyPage/MyPage.module.scss
Labels: feat

#84 [소혜린] Feat: 크레딧 localStorage에 저장기능 개발
  package-lock.json
  package.json
  src/components/Modal/CreditChargeModal/CreditChargeModal.jsx
  src/components/Modal/VoteModal/VoteModal.jsx
  src/context/jotai.js
  src/pages/List/ChartSection.jsx
  src/pages/List/CreditSection.jsx
Labels: feat

#79 [이율] Feat: support section 모달 연결, 후원하기 기능 추가
  package-lock.json
  package.json
  src/components/Card/SupportCard/SupportCard.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/SupportModal/SupportModal.jsx
  src/context/jotai.js
  src/pages/List/CreditSection.jsx
  src/pages/List/SupportSection.jsx
Labels: feat

#83 [천권희] AddFavoriteSection api 연동
  .env
  src/hooks/useResponsive.js
  src/pages/MyPage/AddFavoriteSection.jsx
  src/pages/MyPage/DeleteIcon.jsx
  src/pages/MyPage/MyPage.jsx
Labels: feat

#86 [천권희] Favorite Idols 추가하기 기능
  package-lock.json
  package.json
  src/context/favoriteIdols.js
  src/pages/MyPage/AddFavoriteSection.jsx
  src/pages/MyPage/AddedFavoriteSection.jsx
Labels: feat

#88 Refactor: scss 미디어 쿼리 수정
  src/components/Navbar/Navbar.module.scss
Labels: refactor

#92 [소혜린] 버그 fix 및 디자인 수정
  src/components/Card/SupportCard.module.scss
  src/components/Card/SupportCard/SupportCard.jsx
  src/components/ChartItem/ChartItem.jsx
  src/components/Image/RectangleImage/RectangleImage.jsx
  src/components/Image/RoundImage/RoundImage.jsx
  src/components/WebpLoader/WebpLoader.jsx
  src/pages/List/ChartSection.jsx
  src/pages/MyPage/MyPage.module.scss
Labels: bug, fix

#93 [이율] Fix: support section 요구사항 적용 및 버그 수정
  src/api/getDonationsData.js
  src/components/Button/ArrowButton/ArrowButton.jsx
  src/components/Button/Button.module.scss
  src/components/Card/SupportCard.module.scss
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/SupportModal/SupportModal.jsx
  src/pages/List/ChartSection.jsx
  src/pages/List/List.module.scss
  src/pages/List/SupportSection.jsx
  src/pages/MyPage/AddFavoriteSection.jsx
Labels: bug

#95 [천권희] Fix: MyPage 수정
  src/pages/List/CreditSection.jsx
  src/pages/MyPage/AddFavoriteSection.jsx
  src/pages/MyPage/MyPage.jsx
Labels: bug, fix

#100 Fix: logo 새로고침 기능 구현, mypage에서 logo 경로 수정
  src/components/ChartItem/ChartItem.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.scss
  src/pages/List/ChartSection.jsx
Labels: fix

#101 [이율] ListPage > SupportSection, ChartSection 버그 수정
  src/components/Card/SupportCard/SupportCard.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/SupportModal/SupportModal.jsx
  src/components/Modal/VoteModal/VoteModal.jsx
  src/pages/List/ChartSection.jsx
Labels: bug

#103 [소혜린] TouchArea Context 사용 및 ChartSeciton 에러메세지 표시
  src/App.jsx
  src/components/Modal/CreditChargeModal/CreditChargeModal.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/SupportModal/SupportModal.jsx
  src/components/Modal/VoteModal/VoteModal.jsx
  src/context/Credit.js
  src/context/TouchAreaProvider.jsx
  src/hooks/useLazyImageObserver.js
  src/hooks/useTouchArea.js
  src/pages/List/ChartSection.jsx
  src/pages/List/CreditSection.jsx
  src/pages/List/List.module.scss
  src/pages/List/SupportSection.jsx
  src/pages/MyPage/AddedFavoriteSection.jsx
  src/pages/MyPage/MyPage.module.scss
Labels: feat, refactor

#102 [천권희] AddFavoriteSection Mobile Slider
  src/api/dispatcher.js
  src/components/Button/Button.module.scss
  src/components/Button/RoundButton/RoundButton.jsx
  src/components/Skeleton/AddFavoriteSkeleton/AddFavoriteSkeleton.jsx
  src/components/Skeleton/AddFavoriteSkeleton/index.js
  src/components/Skeleton/Skeleton.module.scss
  src/components/Skeleton/index.js
  src/hooks/useIntersectionObserver.js
  src/hooks/useRequest.js
  src/hooks/useSlider.js
  src/pages/MyPage/AddFavoriteSection.jsx
  src/pages/MyPage/MyPage.module.scss
  src/styles/common.scss
Labels: feat

#105 [이율] Fix : supportSection 레이지로딩 시 엑박 뜨는 문제
  src/assets/default_image.png
  src/components/Image/RectangleImage/RectangleImage.jsx
  src/components/WebpLoader/WebpLoader.jsx
  src/pages/List/ChartSection.jsx
  src/pages/List/List.module.scss
Labels: bug

#113 Fix: Support Section Skeleton
  src/pages/List/SupportSection.jsx
Labels: fix

#111 [천권희] Meta Tag 설정
  public/favicon.ico
  public/index.html
  src/hooks/useRequest.js
  src/styles/common.scss
Labels: feat

#115 [소혜린] 모달창 외부 스크롤 방지
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
Labels: feat, design

#116 [소혜린] useLazyImageObserver.js 예외 처리
  src/hooks/useLazyImageObserver.js
Labels: bug

#117 Fix: Favicon 변경
  public/favicon.ico
  public/index.html
Labels: fix

#118 [이율] Fix: SupportSection 가로 1200px에서 버튼 가려지는 문제
  src/pages/List/List.module.scss
Labels: bug

#119 Fix: fix default credit
  src/context/Credit.js
Labels: fix

#120 Fix(AddFavoriteSection): disabled arrow button
  src/components/Button/index.js
  src/pages/MyPage/AddFavoriteSection.jsx
Labels: fix

#121 main 브랜치 2차 병합
  public/favicon.ico
  public/index.html
  src/components/Button/index.js
  src/context/Credit.js
  src/pages/List/List.module.scss
  src/pages/MyPage/AddFavoriteSection.jsx
Labels: chore
